### ISSUE TITLE
[Bug]1.16.5+Apotheosis

### ISSUE THREAD

**Issue by 2929762171** [Jackiecrazy/ArmorCurve#5]
armorcurve-2.4
Apotheosis-1.16.5-4.8.9A0
Mainly crash with **CatServer-1.16.5-98eabb0e-server.jar** ,
work normally on forge server(forge-1.16.5-36.2.39).
(But CatServer has better performance.)

【1】Crash with magic arrow:
![image](https://github.com/Jackiecrazy/ArmorCurve/assets/98941945/88cab188-abb0-4341-a96c-efdee3acccbf)
[Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1061) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:336) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:943) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ArithmeticException: Division undefined
	at java.math.BigDecimal.divide(BigDecimal.java:1773) ~[?:?]
	at com.udojava.evalex.apothavoidance.Expression$6.eval(Expression.java:587) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractOperator$1.eval(AbstractOperator.java:70) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression$68.eval(Expression.java:1433) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractFunction$1.getParams(AbstractFunction.java:88) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractFunction$1.eval(AbstractFunction.java:77) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractOperator$1.eval(AbstractOperator.java:70) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression$68.eval(Expression.java:1433) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractOperator$1.eval(AbstractOperator.java:70) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression$68.eval(Expression.java:1433) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression.eval(Expression.java:1521) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression.eval(Expression.java:1397) ~[armorcurve:2.4]
	at net.minecraft.util.CombatRules.handler$zek000$getDamageLeft(SourceFile:517) ~[?:?]
	at net.minecraft.util.CombatRules.func_189427_a(SourceFile) ~[?:?]
	at net.minecraft.entity.LivingEntity.getDamageAfterArmorAbsorb(LivingEntity.java:1714) ~[?:?]
	at net.minecraft.entity.LivingEntity.lambda$damageEntity0$8(LivingEntity.java:1809) ~[?:?]
	at net.minecraft.entity.LivingEntity.damageEntity0(LivingEntity.java:1810) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1188) ~[?:?]
	at com.lycanitesmobs.core.entity.BaseCreatureEntity.func_70097_a(BaseCreatureEntity.java:3208) ~[lycanitesmobs:1.16.5-2.3.3.3]
	at com.lycanitesmobs.core.entity.TameableCreatureEntity.func_70097_a(TameableCreatureEntity.java:674) ~[lycanitesmobs:1.16.5-2.3.3.3]
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:343) ~[?:?]
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(ProjectileEntity.java:131) ~[?:?]
	at net.minecraft.entity.projectile.ProjectileEntity.preOnHit(ProjectileEntity.java:122) ~[?:?]
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:196) ~[?:?]
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(ArrowEntity.java:107) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:756) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:2492) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:529) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1049) ~[?:?]
	... 5 more
[13:22:01] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: \tCause of unexpected exception was
java.lang.ArithmeticException: Division undefined
	at java.math.BigDecimal.divide(BigDecimal.java:1773) ~[?:?]
	at com.udojava.evalex.apothavoidance.Expression$6.eval(Expression.java:587) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractOperator$1.eval(AbstractOperator.java:70) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression$68.eval(Expression.java:1433) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractFunction$1.getParams(AbstractFunction.java:88) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractFunction$1.eval(AbstractFunction.java:77) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractOperator$1.eval(AbstractOperator.java:70) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression$68.eval(Expression.java:1433) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractOperator$1.eval(AbstractOperator.java:70) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression$68.eval(Expression.java:1433) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression.eval(Expression.java:1521) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression.eval(Expression.java:1397) ~[armorcurve:2.4]
	at net.minecraft.util.CombatRules.handler$zek000$getDamageLeft(SourceFile:517) ~[?:?]
	at net.minecraft.util.CombatRules.func_189427_a(SourceFile) ~[?:?]
	at net.minecraft.entity.LivingEntity.getDamageAfterArmorAbsorb(LivingEntity.java:1714) ~[?:?]
	at net.minecraft.entity.LivingEntity.lambda$damageEntity0$8(LivingEntity.java:1809) ~[?:?]
	at net.minecraft.entity.LivingEntity.damageEntity0(LivingEntity.java:1810) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1188) ~[?:?]
	at com.lycanitesmobs.core.entity.BaseCreatureEntity.func_70097_a(BaseCreatureEntity.java:3208) ~[lycanitesmobs:1.16.5-2.3.3.3]
	at com.lycanitesmobs.core.entity.TameableCreatureEntity.func_70097_a(TameableCreatureEntity.java:674) ~[lycanitesmobs:1.16.5-2.3.3.3]
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:343) ~[?:?]
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(ProjectileEntity.java:131) ~[?:?]
	at net.minecraft.entity.projectile.ProjectileEntity.preOnHit(ProjectileEntity.java:122) ~[?:?]
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:196) ~[?:?]
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(ArrowEntity.java:107) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:756) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:2492) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:529) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1049) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:336) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:943) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

【2】"Dolphin"? Maybe a mob did this..
![image](https://github.com/Jackiecrazy/ArmorCurve/assets/98941945/934d2bbf-33ad-4f5d-bb04-6735efa4c81c)
[Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1061) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:336) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:943) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ArithmeticException: Division undefined
	at java.math.BigDecimal.divide(BigDecimal.java:1773) ~[?:?]
	at com.udojava.evalex.apothavoidance.Expression$6.eval(Expression.java:587) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractOperator$1.eval(AbstractOperator.java:70) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression$68.eval(Expression.java:1433) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractFunction$1.getParams(AbstractFunction.java:88) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractFunction$1.eval(AbstractFunction.java:77) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractOperator$1.eval(AbstractOperator.java:70) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression$68.eval(Expression.java:1433) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractOperator$1.eval(AbstractOperator.java:70) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression$68.eval(Expression.java:1433) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression.eval(Expression.java:1521) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression.eval(Expression.java:1397) ~[armorcurve:2.4]
	at net.minecraft.util.CombatRules.handler$zek000$getDamageLeft(SourceFile:517) ~[?:?]
	at net.minecraft.util.CombatRules.func_189427_a(SourceFile) ~[?:?]
	at net.minecraft.entity.LivingEntity.getDamageAfterArmorAbsorb(LivingEntity.java:1714) ~[?:?]
	at net.minecraft.entity.LivingEntity.lambda$damageEntity0$8(LivingEntity.java:1809) ~[?:?]
	at net.minecraft.entity.LivingEntity.damageEntity0(LivingEntity.java:1810) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1188) ~[?:?]
	at net.minecraft.entity.passive.DolphinEntity.func_70652_k(DolphinEntity.java:180) ~[?:?]
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_190102_a(MeleeAttackGoal.java:138) ~[?:?]
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:130) ~[?:?]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.tickGoals(SourceFile:649) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:556) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:756) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2878) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:547) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2622) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:343) ~[?:?]
	at net.minecraft.entity.passive.DolphinEntity.func_70071_h_(DolphinEntity.java:243) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:756) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:2492) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:529) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1049) ~[?:?]
	... 5 more
[22:19:24] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: \tCause of unexpected exception was
java.lang.ArithmeticException: Division undefined
	at java.math.BigDecimal.divide(BigDecimal.java:1773) ~[?:?]
	at com.udojava.evalex.apothavoidance.Expression$6.eval(Expression.java:587) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractOperator$1.eval(AbstractOperator.java:70) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression$68.eval(Expression.java:1433) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractFunction$1.getParams(AbstractFunction.java:88) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractFunction$1.eval(AbstractFunction.java:77) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractOperator$1.eval(AbstractOperator.java:70) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression$68.eval(Expression.java:1433) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.AbstractOperator$1.eval(AbstractOperator.java:70) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression$68.eval(Expression.java:1433) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression.eval(Expression.java:1521) ~[armorcurve:2.4]
	at com.udojava.evalex.apothavoidance.Expression.eval(Expression.java:1397) ~[armorcurve:2.4]
	at net.minecraft.util.CombatRules.handler$zek000$getDamageLeft(SourceFile:517) ~[?:?]
	at net.minecraft.util.CombatRules.func_189427_a(SourceFile) ~[?:?]
	at net.minecraft.entity.LivingEntity.getDamageAfterArmorAbsorb(LivingEntity.java:1714) ~[?:?]
	at net.minecraft.entity.LivingEntity.lambda$damageEntity0$8(LivingEntity.java:1809) ~[?:?]
	at net.minecraft.entity.LivingEntity.damageEntity0(LivingEntity.java:1810) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:1188) ~[?:?]
	at net.minecraft.entity.passive.DolphinEntity.func_70652_k(DolphinEntity.java:180) ~[?:?]
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_190102_a(MeleeAttackGoal.java:138) ~[?:?]
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:130) ~[?:?]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.tickGoals(SourceFile:649) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:556) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:756) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2878) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:547) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2622) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:343) ~[?:?]
	at net.minecraft.entity.passive.DolphinEntity.func_70071_h_(DolphinEntity.java:243) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:756) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:2492) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:529) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1049) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:336) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:943) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Jackiecrazy** [comment]
`at com.udojava.evalex.apothavoidance.`
This is pointing to Apotheosis. Also, 1.16 is no longer supported.
